## 异常

使用throw抛出一个异常(java.lang.Throwable实例)

    throw new IllegalArgumentException("x should be a number")
    
 scala并不会在编译器检查异常，所以不存在checked exception和unchecked exception的区别，也不需要在方法签名中声明他可能抛出的checked exception
 
    def throwEx()={
        throw new IllegalArgumentException("x should be a number")
    }
    
  throw 表达式的返回值是Nothing类型，这在if/else表达式中很有用：一个分支的返回值是Nothing，则if/else表达式的返回值类型是另一个分支的结果类型
  
    var sqrtNum = if(x>0){
        sqrt(x)
    }else throw new IllegalArgumentException("x should be negative ")
    
  使用try/catch/finally表达式捕获异常
  
    val table = new HTable("user")
    try{
        table.flushCommits()
    }catch{
        case re:RetriesExhaustedWithDetailsException => log.error("failed to insert data to hbase")
        case _:Throwable => log.error("insert data to hbase encountered an unexpected error")
    }finally{
        table.close()
    }